export type CaseStudyMetric = { value: string; label: string };
export type CaseStudy = {
  slug: string; title: string; client: string; industry: string; summary: string;
  thumbnail: string; images: string[]; metrics: CaseStudyMetric[];
  challenge: string; approach: string[]; outcome: string;
};

export const caseStudies: CaseStudy[] = [
  { slug: 'yalaride', title: 'YalaRide', client: 'YalaRide Ltd', industry: 'Transportation', summary: 'A premium ride-sharing platform built around fast booking, live trip visibility, and a calmer passenger experience.', thumbnail: '/uploads/yalaride-thumb.jpg', images: ['/uploads/yalaride-1.jpg', '/uploads/yalaride-2.jpg'], metrics: [{ value: '50K+', label: 'downloads' }, { value: '4.8', label: 'app rating' }], challenge: 'Turn a complex dispatch workflow into a simple mobile experience while keeping riders and drivers informed in real time.', approach: ['Mapped the booking journey around the moments that create rider uncertainty.', 'Designed a mobile-first interface with clear trip states and live feedback.', 'Structured the platform for dependable location updates and future service expansion.'], outcome: 'YalaRide launched with a focused booking experience that supported rapid adoption and strong customer ratings.' },
  { slug: 'america-needs-nurses', title: 'America Needs Nurses', client: 'ANN Recruitment', industry: 'Healthcare', summary: 'A healthcare recruitment experience that connects qualified nurses with facilities that need them.', thumbnail: '/uploads/nurses-thumb.jpg', images: ['/uploads/nurses-1.jpg'], metrics: [{ value: '200+', label: 'placements' }, { value: '95%', label: 'success rate' }], challenge: 'Reduce friction across a high-trust recruitment process involving candidates, credentials, and healthcare employers.', approach: ['Clarified the candidate journey from discovery through placement.', 'Made role requirements and next steps easier to understand.', 'Created a scalable foundation for recruitment campaigns and lead qualification.'], outcome: 'The rebuilt journey made the service easier to navigate and helped the team convert interest into successful placements.' },
  { slug: 'go-jetter-tours', title: 'Go Jetter Tours', client: 'GoJetter Tours', industry: 'Travel', summary: 'A travel booking platform that helps customers move from inspiration to a managed itinerary.', thumbnail: '/uploads/travel-thumb.jpg', images: ['/uploads/travel-1.jpg'], metrics: [{ value: '10K+', label: 'bookings' }, { value: '4.9', label: 'customer rating' }], challenge: 'Make a broad catalog of destinations and travel choices feel personal without complicating the path to booking.', approach: ['Organized discovery around traveler intent rather than inventory.', 'Created a consistent flow from recommendation to itinerary.', 'Prioritized responsive performance for customers planning on mobile devices.'], outcome: 'The experience gave travelers a clearer path to purchase and supported sustained booking growth.' },
  { slug: 'atlanta-car-rental', title: 'Atlanta Car Rental', client: 'Atlanta Car Services', industry: 'Automotive', summary: 'A fleet and reservation experience designed to keep availability, booking, and operations in sync.', thumbnail: '/uploads/rental-thumb.jpg', images: [], metrics: [{ value: '5K+', label: 'rentals' }, { value: '98%', label: 'satisfaction' }], challenge: 'Replace fragmented fleet and reservation workflows with one understandable customer and operator journey.', approach: ['Connected vehicle discovery to real availability.', 'Simplified booking details and confirmation states.', 'Designed operational views around the decisions staff make most often.'], outcome: 'The platform reduced booking friction while giving the team a more reliable view of fleet activity.' },
  { slug: 'cars-compound', title: 'Cars Compound', client: 'Cars Compound Inc', industry: 'E-commerce', summary: 'A digital showroom for high-value vehicles, built to make discovery and financing feel considered.', thumbnail: '/uploads/dealership-thumb.jpg', images: [], metrics: [{ value: '$2M+', label: 'sales' }, { value: '300+', label: 'vehicles' }], challenge: 'Bring the confidence and detail of an in-person luxury showroom into an online buying journey.', approach: ['Elevated vehicle imagery and key specifications.', 'Built useful pathways for inventory search and comparison.', 'Integrated inquiry and financing moments without disrupting discovery.'], outcome: 'The new showroom supported a growing catalog and helped translate online attention into high-value sales conversations.' },
  { slug: 'vipkars', title: 'VIPkars', client: 'VIPkars Rent', industry: 'Transportation', summary: 'A concierge-led premium rental experience for clients who expect speed, discretion, and service.', thumbnail: '/uploads/vip-thumb.jpg', images: [], metrics: [{ value: '1K+', label: 'clients' }, { value: '5-star', label: 'service' }], challenge: 'Express a high-touch service model digitally while keeping the reservation path immediate and practical.', approach: ['Established a confident luxury visual system.', 'Reduced the reservation journey to essential decisions.', 'Made concierge support visible at the moments where it adds trust.'], outcome: 'VIPkars gained a digital experience aligned with its premium service and repeat-client expectations.' },
  { slug: 'priceless-rent-a-car', title: 'Priceless Rent A Car', client: 'Priceless Rent', industry: 'Automotive', summary: 'A straightforward rental platform balancing competitive pricing with a dependable booking experience.', thumbnail: '/uploads/priceless-thumb.jpg', images: [], metrics: [{ value: '8K+', label: 'rentals' }, { value: '4.7', label: 'customer rating' }], challenge: 'Help value-conscious customers compare options quickly without making the service feel transactional or uncertain.', approach: ['Made pricing and vehicle differences easier to scan.', 'Removed avoidable steps from booking.', 'Used clear reassurance around policies, availability, and support.'], outcome: 'Customers gained a faster path to the right vehicle, supporting rental volume and consistently positive ratings.' },
];

export const getCaseStudy = (slug: string) => caseStudies.find((study) => study.slug === slug);
